package com.nvisia.sample.dao;

import com.nvisia.sample.dto.Person;

/**
 * Interface used to define the methods available to access {@link Person} data.
 * This interface is used to abstract the actual persistence mechanism that is
 * used to actually store/retrieve {@link Person} data.
 */
public interface PersonDAO {

	/**
	 * Method used for standard primary key lookup.
	 * 
	 * @param identifier
	 *            The primary key of the {@link Person} instance.
	 * @return Returns the Person instance associated with the identifier, or
	 *         null if no data can be found
	 */
	Person findById(Long identifier);
	
	/**
	 * Method used to save off data related to a {@link Person} instance.
	 * 
	 * @param person
	 *            The person instance to be saved.
	 * @return Returns the identifier that was generated by the persistent store
	 *         when the person was added.
	 */
	Long save(Person person);
	
	/**
	 * Method used to up a person instance that was previous loaded, modified
	 * and is ready to be stored.
	 * 
	 * @param person
	 *            The person instance that was modified.
	 */
	void update(Person person);
	
	/**
	 * Method used to delete a {@link Person} instance by its primary key
	 * identifier.
	 * 
	 * @param identifier
	 *            The primary key of the {@link Person} instance.
	 */
	void delete(Long identifier);
}
